config/routes.rb
Howto::Application.routes.draw do
  resources :howtolists do
    resources :steps
  end

  root :to => 'howtolists#index'

end

app/models/howtolist.rb
class Howtolist < ActiveRecord::Base
  attr_accessible :how_to

  has_many :steps, :dependent => :delete_all
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :howtolist
  attr_accessible :content, :number

  validates :number, :presence => true
  validates :content, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/howtolists_controller.rb
class HowtolistsController < ApplicationController
  # GET /howtolists
  # GET /howtolists.json
  def index
    @howtolists = Howtolist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @howtolists }
    end
  end

  # GET /howtolists/1
  # GET /howtolists/1.json
  def show
    @howtolist = Howtolist.find(params[:id])

    respond_to do |format|
      format.html #show.html.erb
      format.json { render json: @howtolist }
    end
  end

  # GET /howtolists/new
  # GET /howtolists/new.json
  def new
    @howtolist = Howtolist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @howtolist }
    end
  end

  # GET /howtolists/1/edit
  def edit
    @howtolist = Howtolist.find(params[:id])
  end

  # POST /howtolists
  # POST /howtolists.json
  def create
    @howtolist = Howtolist.new(params[:howtolist])

    respond_to do |format|
      if @howtolist.save
        format.html { redirect_to @howtolist, notice: 'Howtolist was successfully created.' }
        format.json { render json: @howtolist, status: :created, location: @howtolist }
      else
        format.html { render action: "new" }
        format.json { render json: @howtolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /howtolists/1
  # PUT /howtolists/1.json
  def update
    @howtolist = Howtolist.find(params[:id])

    respond_to do |format|
      if @howtolist.update_attributes(params[:howtolist])
        format.html { redirect_to @howtolist, notice: 'Howtolist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @howtolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /howtolists/1
  # DELETE /howtolists/1.json
  def destroy
    @howtolist = Howtolist.find(params[:id])
    @howtolist.destroy

    respond_to do |format|
      format.html { redirect_to howtolists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_filter :find_howtolist
  before_filter :find_step, :only => [:show, :edit, :update, :destroy]



  def show
  end

  def new
    @step = @howtolist.steps.build
  end

  def create
    @step = @howtolist.steps.build(params[:step])
    if @step.save
     # flash[:notice] = "Step has been created."
      redirect_to [@howtolist, @step]
    else
    #  flash[:alert] = "Step has not been created."
      render :action => "new"
    end
  end

  def edit

  end

  def update
    if @step.update_attributes(params[:step])
      flash[:notice] = "Step has been updated."
      redirect_to [@howtolist, @step]
    else
      flash[:alert] = "Step has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @step.destroy
    flash[:notice] = "Step has been deleted."
    redirect_to @howtolist
  end

  private
    def find_howtolist
      @howtolist = Howtolist.find(params[:howtolist_id])
    end

    def find_step
      @step = @howtolist.steps.find(params[:id])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/howtolists_helper.rb
module HowtolistsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/howtolists/_form.html.erb
<%= form_for(@howtolist) do |f| %>
  <% if @howtolist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@howtolist.errors.count, "error") %> prohibited this howtolist from being saved:</h2>

      <ul>
      <% @howtolist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :how_to %><br />
    <%= f.text_field :how_to %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/howtolists/edit.html.erb
<h1>Editing howtolist</h1>

<%= render 'form' %>

<%= link_to 'Show', @howtolist %> |
<%= link_to 'Back', howtolists_path %>

app/views/howtolists/index.html.erb
<h1>Listing howtolists</h1>

<table>
  <tr>
    <th>How to</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @howtolists.each do |howtolist| %>
  <tr>
    <td><%= howtolist.how_to %></td>
    <td><%= link_to 'Show', howtolist %></td>
    <td><%= link_to 'Edit', edit_howtolist_path(howtolist) %></td>
    <td><%= link_to 'Destroy', howtolist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Howtolist', new_howtolist_path %>

app/views/howtolists/new.html.erb
<h1>New howtolist</h1>

<%= render 'form' %>

<%= link_to 'Back', howtolists_path %>

app/views/howtolists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>How to:</b>
  <%= @howtolist.how_to %>
</p>


<%= link_to 'Edit', edit_howtolist_path(@howtolist) %> |
<%= link_to 'Back', howtolists_path %>
<%= link_to "New Step", new_howtolist_step_path(@howtolist) %>

<ul id='steps'>
<% @howtolist.steps.each do |step| %>
<li>
#<%= step.id %> -
<%= link_to step.number, [@howtolist, step] %>
</li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Howto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
<%= form_for [@howtolist, @step] do |f| %>
<p>
<%= f.label :number %><br>
<%= f.text_field :number %>
</p>
<p>
<%= f.label :content %><br>
<%= f.text_area :content %>
</p>
<%= f.submit %>
<% end %>

app/views/steps/edit.html.erb
<h2>Editing a step in <%= @howtolist.how_to %></h2>
<% render "form" %>

app/views/steps/new.html.erb
<h2>New Step</h2>
<%= render "form" %>

app/views/steps/show.html.erb
<div id='step'>
<h2><%= @step.number %></h2>
<%= @step.content %>
</div>

<%= link_to "Edit Step", [:edit, @howtolist, @step] %>
<%= link_to "Delete Step", [@howtolist, @step], :method => :delete, :confirm => "Are you sure you want to delete this step" %>